version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_app.sh
      timeout: 300
      runas: root