version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: app/start_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: app/stop_app.sh
      timeout: 300
      runas: ec2-user