version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn install
  post_build:
    commands:
    - echo Build completed on `date`
reports:
  jacoco-report:
    files:
      - 'target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
artifacts:
  files:
  - target/admin-0.0.1-SNAPSHOT.jar
  - scripts/*.sh
  - appspec.yml
  - amazon-cloudwatch-agent.json
  discard-paths: yes
